title: PGroonga
markdown: kramdown
highlighter: pygments
pgroonga_version: 1.0.1
pgroonga_release_date: 2015-12-29
copyright_year: 2015-2016
postgresql_short_version: 9.4
windows_postgresql_version: 9.4.5-1
windows_postgresql_short_version: 9.4
exclude: ["Rakefile", "Gemfile", "Gemfile.lock"]
description:
  en: Make PostgreSQL fast full text search platform for all languages!
  ja: PostgreSQLで高速日本語全文検索！

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
  coderay_line_numbers: nil

sass:
  sass_dir: assets/stylesheets
