title: PGroonga
markdown: kramdown
highlighter: pygments
pgroonga_version: 0.7.0
pgroonga_release_date: 2015-07-10
copyright_year: 2015
postgresql_short_version: 9.4
windows_postgresql_version: 9.4.4-1
exclude: ["Rakefile", "Gemfile", "Gemfile.lock"]
description: A PostgreSQL extension to use Groonga as index

kramdown:
  input: GFM
