title: PGroonga
markdown: kramdown
highlighter: rouge
pgroonga_version: 1.1.9
pgroonga_release_date: 2016-11-30
copyright_year: 2015-2017
postgresql_short_version: 9.6
postgresql_doc_base_url:
  en: https://www.postgresql.org/docs/9.6/static
  ja: https://www.postgresql.jp/document/9.6/html
windows_postgresql_versions:
  - 9.5.6-2
  - 9.6.2-3
freebsd_postgresql_version: 96
centos_groonga_release_version: 1.3.0-1
exclude:
  - "Rakefile"
  - "Gemfile"
  - "Gemfile.lock"
  - "data"
description:
  en: Make PostgreSQL fast full text search platform for all languages!
  ja: PostgreSQLで高速日本語全文検索！

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]

sass:
  sass_dir: assets/stylesheets

defaults:
  - scope:
      path: "ja"
    values:
      path_prefix: /ja/
      layout: "base"
      language: ja
      country: JP
  - scope:
      path: ""
    values:
      path_prefix: /
      layout: "base"
      language: en
      country: US
