title: PGroonga
markdown: kramdown
highlighter: pygments
pgroonga_version: 0.5.0
pgroonga_release_date: 2015-04-29
copyright_year: 2015
postgresql_short_version: 9.4
windows_postgresql_version: 9.4.1-3
exclude: ["Rakefile", "Gemfile", "Gemfile.lock"]
description: A PostgreSQL extension to use Groonga as index

kramdown:
  input: GFM
