title: PGroonga
markdown: kramdown
pgroonga_version: 0.5.0
exclude: ["Rakefile", "Gemfile", "Gemfile.lock"]
description: A PostgreSQL plugin to use Groonga as index

kramdown:
  enable_coderay: true
  coderay_line_numbers: table
