title: PGroonga
markdown: kramdown
highlighter: rouge
pgroonga_version: 1.0.7
pgroonga_release_date: 2016-04-24
copyright_year: 2015-2016
postgresql_short_version: 9.5
windows_postgresql_version: 9.5.2-1
windows_postgresql_short_version: 9.5
exclude: ["Rakefile", "Gemfile", "Gemfile.lock"]
description:
  en: Make PostgreSQL fast full text search platform for all languages!
  ja: PostgreSQLで高速日本語全文検索！

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]

sass:
  sass_dir: assets/stylesheets
